# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update ReadMe every midnight

on:
  schedule:
    - cron: '0 0 * * *'
  push: 
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - run: |
        cd repo-info-script
        npm install 
        node script.js
        cd ..
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${ACCESS_TOKEN}@github.com/Jadid-Alam/Jadid-Alam.git
        git add README.md
        git diff --quiet && echo "No changes" || git commit -m "Daily automated update"
        git push origin main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
